language: node_js
node_js:
  - "8"
  - "10"

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Firefox-addon-in-headless-mode
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

script:
  - yarn
  - yarn run bootstrap
  - yarn run ci
